//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add an environment.
        /// </summary>
        internal static string addBackupEnvironment {
            get {
                return ResourceManager.GetString("addBackupEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string BackupType {
            get {
                return ResourceManager.GetString("BackupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business softwares.
        /// </summary>
        internal static string businessSoftwaresButton {
            get {
                return ResourceManager.GetString("businessSoftwaresButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main menu.
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a backup type:.
        /// </summary>
        internal static string chooseBackupLabel {
            get {
                return ResourceManager.GetString("chooseBackupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        internal static string confirmButton {
            get {
                return ResourceManager.GetString("confirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description (optional).
        /// </summary>
        internal static string decriptionLabel {
            get {
                return ResourceManager.GetString("decriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete this environment.
        /// </summary>
        internal static string deleteBackupEnvironment {
            get {
                return ResourceManager.GetString("deleteBackupEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination directory.
        /// </summary>
        internal static string destinationDirectoryLabel {
            get {
                return ResourceManager.GetString("destinationDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential backup.
        /// </summary>
        internal static string differentialBackup {
            get {
                return ResourceManager.GetString("differentialBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Environments.
        /// </summary>
        internal static string EnvironmentName {
            get {
                return ResourceManager.GetString("EnvironmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Environments.
        /// </summary>
        internal static string Environments {
            get {
                return ResourceManager.GetString("Environments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run backup.
        /// </summary>
        internal static string executeBackup {
            get {
                return ResourceManager.GetString("executeBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Files to encrypt.
        /// </summary>
        internal static string filesToEncryptButton {
            get {
                return ResourceManager.GetString("filesToEncryptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full backup.
        /// </summary>
        internal static string fullBackup {
            get {
                return ResourceManager.GetString("fullBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A business software has been detected!.
        /// </summary>
        internal static string mbBusinessSoftwware {
            get {
                return ResourceManager.GetString("mbBusinessSoftwware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You first need to run a full backup!.
        /// </summary>
        internal static string mbCheckFullBackup {
            get {
                return ResourceManager.GetString("mbCheckFullBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The .
        /// </summary>
        internal static string mbCreatedView1 {
            get {
                return ResourceManager.GetString("mbCreatedView1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  environment has been created..
        /// </summary>
        internal static string mbCreatedView2 {
            get {
                return ResourceManager.GetString("mbCreatedView2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The differential backup has been done..
        /// </summary>
        internal static string mbDifferentialBackup {
            get {
                return ResourceManager.GetString("mbDifferentialBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The full backup has been done..
        /// </summary>
        internal static string mbFullBackup {
            get {
                return ResourceManager.GetString("mbFullBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The restore of the backup has been done..
        /// </summary>
        internal static string mbRestore {
            get {
                return ResourceManager.GetString("mbRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All the backups have been done..
        /// </summary>
        internal static string mbRunMultipleBackup {
            get {
                return ResourceManager.GetString("mbRunMultipleBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The name format is incorrect! (between 3 to 35 characters) .
        /// </summary>
        internal static string mbWrongFormat {
            get {
                return ResourceManager.GetString("mbWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information incorrect!.
        /// </summary>
        internal static string mbWrongInfos {
            get {
                return ResourceManager.GetString("mbWrongInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string nameLabel {
            get {
                return ResourceManager.GetString("nameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No backup.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full backup.
        /// </summary>
        internal static string radioButton1 {
            get {
                return ResourceManager.GetString("radioButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential backup.
        /// </summary>
        internal static string radioButton2 {
            get {
                return ResourceManager.GetString("radioButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restore a backup.
        /// </summary>
        internal static string restoreBackup {
            get {
                return ResourceManager.GetString("restoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restore a backup.
        /// </summary>
        internal static string restoreButton {
            get {
                return ResourceManager.GetString("restoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main menu.
        /// </summary>
        internal static string returnMenuButton {
            get {
                return ResourceManager.GetString("returnMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run a backup.
        /// </summary>
        internal static string runBackup {
            get {
                return ResourceManager.GetString("runBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run backups.
        /// </summary>
        internal static string runBackups {
            get {
                return ResourceManager.GetString("runBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run multiple backups.
        /// </summary>
        internal static string runMultipleBackup {
            get {
                return ResourceManager.GetString("runMultipleBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search....
        /// </summary>
        internal static string searchBarLabel {
            get {
                return ResourceManager.GetString("searchBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string settingsLabel {
            get {
                return ResourceManager.GetString("settingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source directory.
        /// </summary>
        internal static string sourceDirectoryLabel {
            get {
                return ResourceManager.GetString("sourceDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If they are detected,.
        /// </summary>
        internal static string subtitleBusinessSoftwares1 {
            get {
                return ResourceManager.GetString("subtitleBusinessSoftwares1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à you will not be able to run a backup..
        /// </summary>
        internal static string subtitleBusinessSoftwares2 {
            get {
                return ResourceManager.GetString("subtitleBusinessSoftwares2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All files within these extensions will be encrypted..
        /// </summary>
        internal static string subtitleExtentions {
            get {
                return ResourceManager.GetString("subtitleExtentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Define business softwares.
        /// </summary>
        internal static string titleBusinessSoftwares {
            get {
                return ResourceManager.GetString("titleBusinessSoftwares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Define extensions.
        /// </summary>
        internal static string titleExtentions {
            get {
                return ResourceManager.GetString("titleExtentions", resourceCulture);
            }
        }
    }
}
