//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New environment.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup.
        /// </summary>
        internal static string BackupColumn {
            get {
                return ResourceManager.GetString("BackupColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string BusinessSoftwareAdd {
            get {
                return ResourceManager.GetString("BusinessSoftwareAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business software.
        /// </summary>
        internal static string BusinessSoftwareLabel {
            get {
                return ResourceManager.GetString("BusinessSoftwareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        internal static string BusinessSoftwareRemove {
            get {
                return ResourceManager.GetString("BusinessSoftwareRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        internal static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a backup environment.
        /// </summary>
        internal static string CreateEnvironmentLabel {
            get {
                return ResourceManager.GetString("CreateEnvironmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string CryptAdd {
            get {
                return ResourceManager.GetString("CryptAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encrypted file extensions.
        /// </summary>
        internal static string CryptLabel {
            get {
                return ResourceManager.GetString("CryptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        internal static string CryptRemove {
            get {
                return ResourceManager.GetString("CryptRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To begin with, create an environment and select one in the list..
        /// </summary>
        internal static string DefaultViewLabel {
            get {
                return ResourceManager.GetString("DefaultViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete this environment.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination directory: .
        /// </summary>
        internal static string DestinationDirectoryLabel {
            get {
                return ResourceManager.GetString("DestinationDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run a differential backup.
        /// </summary>
        internal static string DifferentialBackupButton {
            get {
                return ResourceManager.GetString("DifferentialBackupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential backup.
        /// </summary>
        internal static string DifferentialBackupRadio {
            get {
                return ResourceManager.GetString("DifferentialBackupRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Environment.
        /// </summary>
        internal static string EnvironmentColumn {
            get {
                return ResourceManager.GetString("EnvironmentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string EnvName {
            get {
                return ResourceManager.GetString("EnvName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        internal static string FRButton {
            get {
                return ResourceManager.GetString("FRButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run a full backup.
        /// </summary>
        internal static string FullBackupButton {
            get {
                return ResourceManager.GetString("FullBackupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full backup.
        /// </summary>
        internal static string FullBackupRadio {
            get {
                return ResourceManager.GetString("FullBackupRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Environment dashboard.
        /// </summary>
        internal static string groupBox1 {
            get {
                return ResourceManager.GetString("groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup progression.
        /// </summary>
        internal static string groupBox2 {
            get {
                return ResourceManager.GetString("groupBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        internal static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 100 kB.
        /// </summary>
        internal static string Ko100 {
            get {
                return ResourceManager.GetString("Ko100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1.000 kB.
        /// </summary>
        internal static string Ko1000 {
            get {
                return ResourceManager.GetString("Ko1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 10.000 kB.
        /// </summary>
        internal static string Ko10000 {
            get {
                return ResourceManager.GetString("Ko10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 500 kB.
        /// </summary>
        internal static string Ko500 {
            get {
                return ResourceManager.GetString("Ko500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose maximum:.
        /// </summary>
        internal static string KoMax {
            get {
                return ResourceManager.GetString("KoMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blocking file size.
        /// </summary>
        internal static string LimitSizeLabel {
            get {
                return ResourceManager.GetString("LimitSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The .
        /// </summary>
        internal static string mbCreatedEnvironment1 {
            get {
                return ResourceManager.GetString("mbCreatedEnvironment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  environment has been created..
        /// </summary>
        internal static string mbCreatedEnvironment2 {
            get {
                return ResourceManager.GetString("mbCreatedEnvironment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A backup is already running on one of the environments selected!.
        /// </summary>
        internal static string mbRunMultipleBackups {
            get {
                return ResourceManager.GetString("mbRunMultipleBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The name format is incorrect! (between 3 to 35 characters).
        /// </summary>
        internal static string mbWrongFormat {
            get {
                return ResourceManager.GetString("mbWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information incorrect!.
        /// </summary>
        internal static string mbWrongInformation {
            get {
                return ResourceManager.GetString("mbWrongInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name: .
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No backup.
        /// </summary>
        internal static string NoBackupRadio {
            get {
                return ResourceManager.GetString("NoBackupRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause.
        /// </summary>
        internal static string PauseButton {
            get {
                return ResourceManager.GetString("PauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string PriorityAdd {
            get {
                return ResourceManager.GetString("PriorityAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à High priority file extensions.
        /// </summary>
        internal static string PriorityLabel {
            get {
                return ResourceManager.GetString("PriorityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        internal static string PriorityRemove {
            get {
                return ResourceManager.GetString("PriorityRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Progress.
        /// </summary>
        internal static string progressCol {
            get {
                return ResourceManager.GetString("progressCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restore a backup.
        /// </summary>
        internal static string RestoreButton {
            get {
                return ResourceManager.GetString("RestoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resume.
        /// </summary>
        internal static string ResumeButton {
            get {
                return ResourceManager.GetString("ResumeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run all backups.
        /// </summary>
        internal static string RunMultipleBackupsButton {
            get {
                return ResourceManager.GetString("RunMultipleBackupsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run multiple backups.
        /// </summary>
        internal static string RunMultipleBackupsLabel {
            get {
                return ResourceManager.GetString("RunMultipleBackupsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run multiple backups.
        /// </summary>
        internal static string RunMutipleBackupsButton {
            get {
                return ResourceManager.GetString("RunMutipleBackupsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search....
        /// </summary>
        internal static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source directory: .
        /// </summary>
        internal static string SourceDirectoryLabel {
            get {
                return ResourceManager.GetString("SourceDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        internal static string statusCol {
            get {
                return ResourceManager.GetString("statusCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string TypeColumn {
            get {
                return ResourceManager.GetString("TypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string UKButton {
            get {
                return ResourceManager.GetString("UKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome on EasySave!.
        /// </summary>
        internal static string WelcomeLabel {
            get {
                return ResourceManager.GetString("WelcomeLabel", resourceCulture);
            }
        }
    }
}
